name: Java CI with Maven for Insured Assurance

on:
  push:
    branches: [ master ] # Triggers on push to the master branch
  pull_request:
    branches: [ master ] # Triggers on pull requests to the master branch

jobs:
  build_and_test_app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21' # Align with your project's JDK
        distribution: 'temurin'
        cache: 'maven'

    - name: Build with Maven
      run: mvn -B clean package --file pom.xml # -B for batch mode, 'clean' ensures fresh build

    - name: Run tests with Maven
      run: mvn test --file pom.xml # This will run if you have tests and surefire plugin

    - name: Upload application WAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: insured-assurance-war # Artifact name for Jenkins to find
        path: target/*.war # Path to the built WAR file (e.g., target/insured-assurance-app.war)
                           # Ensure this matches your pom.xml's finalName or artifactId
